version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: preorder_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: preorder
      MYSQL_USER: kuk329
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: