version : '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: reservation_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: preorder
      MYSQL_USER: kuk329
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



